### ISSUE TITLE
Issue: Create a monoreopo for Apollon2

### ISSUE THREAD

**Issue by egenerse** [ls1intum/Apollon2#2]
As a developer, I want to have a one repository that has library, server and web app so that I can maintain easily.

### Tasks
- [ ] Create Library 
- [ ] Create Web App
- [ ] Create Server App
- [ ] Setup Workflow for Library
- [ ] Setup Workflow for Web App
- [ ] Setup Workflow for Server App
